version: '3.8'

services:
  backend:
    build:
      context: ./app/backend
      dockerfile: Dockerfile
    container_name: hypeboard_backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development

  frontend:
    build:
      context: ./app/frontend
      dockerfile: Dockerfile
    container_name: hypeboard_frontend
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
